<a href="https://colab.research.google.com/github/Tezz86/Start/blob/main/First_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('bookings.csv', encoding='Windows-1251', sep=';')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 21 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Hotel                      119390 non-null  object
 1   Is Canceled                119390 non-null  int64
 2   Lead Time                  119390 non-null  int64
 3   arrival full date          119390 non-null  object
 4   Arrival Date Year          119390 non-null  int64
 5   Arrival Date Month         119390 non-null  object
 6   Arrival Date Week Number   119390 non-null  int64
 7   Arrival Date Day of Month  119390 non-null  int64
 8   Stays in Weekend nights    119390 non-null  int64
 9   Stays in week nights       119390 non-null  int64
 10  stays total nights         119390 non-null  int64
 11  Adults                     119390 non-null  int64
 12  Children                   119386 non-null  float64
 13  Babies                     119390 non-null  int64
 14  Meal                       119390 non-null  object
 15  Country                    118902 non-null  object
 16  Reserved Room Type         119390 non-null  object
 17  Assigned room type         119390 non-null  object
 18  customer type              119390 non-null  object
 19  Reservation Status         119390 non-null  object
 20  Reservation status_date    119390 non-null  object
dtypes: float64(1), int64(10), object(10)
memory usage: 19.1+ MB

In [ ]:
df.head(7)

,Hotel,Is Canceled,Lead Time,arrival full date,Arrival Date Year,Arrival Date Month,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,...,Adults,Children,Babies,Meal,Country,Reserved Room Type,Assigned room type,customer type,Reservation Status,Reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-03

In [ ]:
def lower_space(title):
  new_title = title.lower().replace(' ','_')
  return new_title

In [ ]:
df = df.rename(columns=lower_space)

In [ ]:
df['country'].unique()

array(['PRT', 'GBR', 'USA', 'ESP', 'IRL', 'FRA', nan, 'ROU', 'NOR', 'OMN',
       'ARG', 'POL', 'DEU', 'BEL', 'CHE', 'CN', 'GRC', 'ITA', 'NLD',
       'DNK', 'RUS', 'SWE', 'AUS', 'EST', 'CZE', 'BRA', 'FIN', 'MOZ',
       'BWA', 'LUX', 'SVN', 'ALB', 'IND', 'CHN', 'MEX', 'MAR', 'UKR',
       'SMR', 'LVA', 'PRI', 'SRB', 'CHL', 'AUT', 'BLR', 'LTU', 'TUR',
       'ZAF', 'AGO', 'ISR', 'CYM', 'ZMB', 'CPV', 'ZWE', 'DZA', 'KOR',
       'CRI', 'HUN', 'ARE', 'TUN', 'JAM', 'HRV', 'HKG', 'IRN', 'GEO',
       'AND', 'GIB', 'URY', 'JEY', 'CAF', 'CYP', 'COL', 'GGY', 'KWT',
       'NGA', 'MDV', 'VEN', 'SVK', 'FJI', 'KAZ', 'PAK', 'IDN', 'LBN',
       'PHL', 'SEN', 'SYC', 'AZE', 'BHR', 'NZL', 'THA', 'DOM', 'MKD',
       'MYS', 'ARM', 'JPN', 'LKA', 'CUB', 'CMR', 'BIH', 'MUS', 'COM',
       'SUR', 'UGA', 'BGR', 'CIV', 'JOR', 'SYR', 'SGP', 'BDI', 'SAU',
       'VNM', 'PLW', 'QAT', 'EGY', 'PER', 'MLT', 'MWI', 'ECU', 'MDG',
       'ISL', 'UZB', 'NPL', 'BHS', 'MAC', 'TGO', 'TWN', 'DJI', 'STP',
       'KNA', 'ETH', 'IRQ', 'HND', 'RWA', 'KHM', 'MCO', 'BGD', 'IMN',
       'TJK', 'NIC', 'BEN', 'VGB', 'TZA', 'GAB', 'GHA', 'TMP', 'GLP',
       'KEN', 'LIE', 'GNB', 'MNE', 'UMI', 'MYT', 'FRO', 'MMR', 'PAN',
       'BFA', 'LBY', 'MLI', 'NAM', 'BOL', 'PRY', 'BRB', 'ABW', 'AIA',
       'SLV', 'DMA', 'PYF', 'GUY', 'LCA', 'ATA', 'GTM', 'ASM', 'MRT',
       'NCL', 'KIR', 'SDN', 'ATF', 'SLE', 'LAO'], dtype=object)

In [ ]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_full_date',
       'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'stays_total_nights', 'adults', 'children',
       'babies', 'meal', 'country', 'reserved_room_type', 'assigned_room_type',
       'customer_type', 'reservation_status', 'reservation_status_date'],
      dtype='object')

In [ ]:
df[df['is_canceled']==1].head(5)

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,adults,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date
8,Resort Hotel,1,85,2015-07-01,2015,July,27,1,0,3,...,2,0.0,0,BB,PRT,A,A,Transient,Canceled,2015-05-06
9,Resort Hotel,1,75,2015-07-01,2015,July,27,1,0,3,...,2,0.0,0,HB,PRT,D,D,Transient,Canceled,2015-04-22
10,Resort Hotel,1,23,2015-07-01,2015,July,27,1,0,4,...,2,0.0,0,BB,PRT,E,E,Transient,Canceled,2015-06-23
27,Resort Hotel,1,60,2015-07-01,2015,July,27,1,2,5,...,2,0.0,0,BB,PRT,E,E,Transient,Canceled,2015-05-11
32,Resort Hotel,1,96,2015-07-01,2015,July,27,1,2,8,...,2,0.0,0,BB,PRT,E,E,Transient,Canceled,2015-05-29

In [ ]:
df[df['is_canceled']==0].country.value_counts()

PRT    21071
GBR     9676
FRA     8481
ESP     6391
DEU     6069
       ...
BHR        1
DJI        1
MLI        1
NPL        1
FRO        1
Name: country, Length: 165, dtype: int64

## Выделяем страны без отмен бронирований

In [ ]:
df.query('is_canceled==0').country.value_counts()

PRT    21071
GBR     9676
FRA     8481
ESP     6391
DEU     6069
       ...
BHR        1
DJI        1
MLI        1
NPL        1
FRO        1
Name: country, Length: 165, dtype: int64

In [ ]:
df.loc[df.is_canceled==0].country.value_counts()

PRT    21071
GBR     9676
FRA     8481
ESP     6391
DEU     6069
       ...
BHR        1
DJI        1
MLI        1
NPL        1
FRO        1
Name: country, Length: 165, dtype: int64

## Среднее количество проведенных ночей по типу отеля

In [ ]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_full_date',
       'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'stays_total_nights', 'adults', 'children',
       'babies', 'meal', 'country', 'reserved_room_type', 'assigned_room_type',
       'customer_type', 'reservation_status', 'reservation_status_date'],
      dtype='object')

In [ ]:
df.groupby('hotel').agg({'stays_total_nights':'mean'}).round(2)

              stays_total_nights
hotel
City Hotel                  2.98
Resort Hotel                4.32

In [ ]:
df.groupby('hotel').stays_total_nights.mean().round(2)

hotel
City Hotel      2.98
Resort Hotel    4.32
Name: stays_total_nights, dtype: float64

## Две колонки с типами комнат. Посчитать сколько раз значения отличаются

### Посмотрим на эти **колонки**

In [ ]:
df[['reserved_room_type','assigned_room_type']]

       reserved_room_type assigned_room_type
0                       C                  C
1                       C                  C
2                       A                  C
3                       A                  A
4                       A                  A
...                   ...                ...
119385                  A                  A
119386                  E                  E
119387                  D                  D
119388                  A                  A
119389                  A                  A

[119390 rows x 2 columns]

### Посчитаем количество различий 1 способом

In [ ]:
df.query('reserved_room_type != assigned_room_type')[['reserved_room_type','assigned_room_type']]

       reserved_room_type assigned_room_type
2                       A                  C
12                      D                  E
15                      D                  E
17                      A                  E
18                      A                  G
...                   ...                ...
119273                  A                  K
119274                  A                  K
119289                  E                  F
119297                  D                  F
119357                  A                  D

[14917 rows x 2 columns]

### Посчитаем количество различий 2 способом

In [ ]:
len(df.loc[df.reserved_room_type != df.assigned_room_type])

14917

### Считаем в каком году какой месяц был самым популярным

In [ ]:
df.groupby('arrival_date_month').agg({'arrival_date_year':'count'})

                    arrival_date_year
arrival_date_month
April                           11089
August                          13877
December                         6780
February                         8068
January                          5929
July                            12661
June                            10939
March                            9794
May                             11791
November                         6794
October                         11160
September                       10508

In [ ]:
df.query('arrival_date_year==2016').arrival_date_month.value_counts()

October      6203
May          5478
April        5428
September    5394
June         5292
August       5063
March        4824
July         4572
November     4454
February     3891
December     3860
January      2248
Name: arrival_date_month, dtype: int64

In [ ]:
df.query('arrival_date_year==2017').arrival_date_month.value_counts()

May         6313
April       5661
June        5647
July        5313
March       4970
August      4925
February    4177
January     3681
Name: arrival_date_month, dtype: int64

In [ ]:
df.groupby('arrival_date_year').arrival_date_month.agg(pd.Series.mode)

arrival_date_year
2015    September
2016      October
2017          May
Name: arrival_date_month, dtype: object

### Считаем какой месяц был самым отменяемым

In [ ]:
df[(df['hotel']=="City Hotel")&(df['is_canceled']==1)].groupby('arrival_date_year').arrival_date_month.agg(pd.Series.mode)

arrival_date_year
2015    September
2016      October
2017          May
Name: arrival_date_month, dtype: object

In [ ]:
df.query('hotel=="City Hotel" and is_canceled==1').groupby('arrival_date_year').arrival_date_month.value_counts()

arrival_date_year  arrival_date_month
2015               September             1543
                   October               1321
                   August                1232
                   July                   939
                   December               668
                   November               301
2016               October               1947
                   June                  1720
                   September             1567
                   April                 1539
                   May                   1436
                   November              1360
                   August                1247
                   March                 1108
                   December              1072
                   July                  1043
                   February               930
                   January                438
2017               May                   2217
                   April                 1926
                   June                  1808
                   July                  1324
                   March                 1278
                   August                1123
                   January               1044
                   February               971
Name: arrival_date_month, dtype: int64

In [ ]:
df.adults.mean()

1.8564033838679956

In [ ]:
df.babies.mean()

0.007948739425412514

In [ ]:
df.children.mean()

0.10388990333874994

In [ ]:
df[['adults','children','babies']].mean()

adults      1.856403
children    0.103890
babies      0.007949
dtype: float64

In [ ]:
df[['adults','children','babies']].describe()

              adults       children         babies
count  119390.000000  119386.000000  119390.000000
mean        1.856403       0.103890       0.007949
std         0.579261       0.398561       0.097436
min         0.000000       0.000000       0.000000
25%         2.000000       0.000000       0.000000
50%         2.000000       0.000000       0.000000
75%         2.000000       0.000000       0.000000
max        55.000000      10.000000      10.000000

In [ ]:
df['total_kids'] = df['children'] + df['babies']

In [ ]:
df['total_kids'].sort_values(ascending=False)

328       10.0
46619     10.0
78656      9.0
19718      3.0
107837     3.0
          ...
119389     0.0
40600      NaN
40667      NaN
40679      NaN
41160      NaN
Name: total_kids, Length: 119390, dtype: float64

In [ ]:
df.total_kids.sort_values(ascending=False).head(10)

328       10.0
46619     10.0
78656      9.0
19718      3.0
107837     3.0
24409      3.0
90790      3.0
95227      3.0
106216     3.0
27246      3.0
Name: total_kids, dtype: float64

In [ ]:
df.iloc[19718]

hotel                        Resort Hotel
is_canceled                             0
lead_time                               0
arrival_full_date              2016-01-01
arrival_date_year                    2016
arrival_date_month                January
arrival_date_week_number                1
arrival_date_day_of_month               1
stays_in_weekend_nights                 0
stays_in_week_nights                    1
stays_total_nights                      1
adults                                  2
children                              3.0
babies                                  0
meal                                   BB
country                               PRT
reserved_room_type                      A
assigned_room_type                      G
customer_type                   Transient
reservation_status              Check-Out
reservation_status_date        2016-01-02
total_kids                            3.0
Name: 19718, dtype: object

In [ ]:
df.groupby('hotel').agg({'total_kids':'mean'}).round(2)

              total_kids
hotel
City Hotel          0.10
Resort Hotel        0.14

In [ ]:
df.query('total_kids>0')

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,children,babies,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date,total_kids
13,Resort Hotel,0,18,2015-07-01,2015,July,27,1,0,4,...,1.0,0,HB,ESP,G,G,Transient,Check-Out,2015-07-05,1.0
45,Resort Hotel,1,47,2015-07-02,2015,July,27,2,2,5,...,2.0,0,BB,PRT,G,G,Transient,Canceled,2015-06-02,2.0
55,Resort Hotel,0,1,2015-07-02,2015,July,27,2,0,1,...,2.0,0,BB,ESP,C,C,Transient,Check-Out,2015-07-03,2.0
65,Resort Hotel,0,10,2015-07-03,2015,July,27,3,0,2,...,2.0,0,BB,USA,G,H,Transient,Check-Out,2015-07-05,2.0
87,Resort Hotel,1,79,2015-07-03,2015,July,27,3,6,15,...,1.0,0,BB,PRT,A,A,Transient,Canceled,2015-04-15,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119270,City Hotel,0,0,2017-08-29,2017,August,35,29,0,3,...,1.0,0,BB,ROU,A,D,Transient,Check-Out,2017-09-01,1.0
119287,City Hotel,0,167,2017-08-27,2017,August,35,27,2,4,...,1.0,0,BB,AUT,D,D,Transient,Check-Out,2017-09-02,1.0
119293,City Hotel,0,243,2017-08-30,2017,August,35,30,0,3,...,2.0,0,BB,DEU,F,F,Transient,Check-Out,2017-09-02,2.0
119318,City Hotel,0,160,2017-08-29,2017,August,35,29,0,5,...,1.0,0,BB,GBR,A,A,Transient,Check-Out,2017-09-03,1.0
119319,City Hotel,0,45,2017-08-28,2017,August,35,28,1,5,...,2.0,0,BB,GBR,F,F,Transient,Check-Out,2017-09-03,2.0

In [ ]:
def has_kids(row):
  if row > 0:
    return True
  return False

In [ ]:
df['has_kids1'] = df.total_kids.apply(has_kids)

In [ ]:
df['has_kids2'] = df.total_kids > 0

In [ ]:
df.shape

(119390, 24)

In [ ]:
df.query('is_canceled==1 and has_kids1==False')

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date,total_kids,has_kids1,has_kids2
8,Resort Hotel,1,85,2015-07-01,2015,July,27,1,0,3,...,BB,PRT,A,A,Transient,Canceled,2015-05-06,0.0,False,False
9,Resort Hotel,1,75,2015-07-01,2015,July,27,1,0,3,...,HB,PRT,D,D,Transient,Canceled,2015-04-22,0.0,False,False
10,Resort Hotel,1,23,2015-07-01,2015,July,27,1,0,4,...,BB,PRT,E,E,Transient,Canceled,2015-06-23,0.0,False,False
27,Resort Hotel,1,60,2015-07-01,2015,July,27,1,2,5,...,BB,PRT,E,E,Transient,Canceled,2015-05-11,0.0,False,False
32,Resort Hotel,1,96,2015-07-01,2015,July,27,1,2,8,...,BB,PRT,E,E,Transient,Canceled,2015-05-29,0.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110280,City Hotel,1,132,2017-04-25,2017,April,17,25,0,0,...,BB,FRA,D,K,Transient,Canceled,2017-04-25,0.0,False,False
111355,City Hotel,1,4,2017-06-05,2017,June,23,5,1,0,...,BB,PRT,A,A,Transient,Canceled,2017-06-05,0.0,False,False
111924,City Hotel,1,7,2017-05-31,2017,May,22,31,0,1,...,BB,PRT,A,A,Transient,Canceled,2017-05-31,0.0,False,False
111925,City Hotel,1,6,2017-07-17,2017,July,29,17,1,0,...,BB,PRT,A,D,Transient,No-Show,2017-07-17,0.0,False,False
117295,City Hotel,1,0,2017-08-02,2017,August,31,2,0,2,...,BB,PRT,A,C,Transient,No-Show,2017-08-02,0.0,False,False

In [ ]:
df.query('is_canceled==1 and has_kids2==False')

,hotel,is_canceled,lead_time,arrival_full_date,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,meal,country,reserved_room_type,assigned_room_type,customer_type,reservation_status,reservation_status_date,total_kids,has_kids1,has_kids2
8,Resort Hotel,1,85,2015-07-01,2015,July,27,1,0,3,...,BB,PRT,A,A,Transient,Canceled,2015-05-06,0.0,False,False
9,Resort Hotel,1,75,2015-07-01,2015,July,27,1,0,3,...,HB,PRT,D,D,Transient,Canceled,2015-04-22,0.0,False,False
10,Resort Hotel,1,23,2015-07-01,2015,July,27,1,0,4,...,BB,PRT,E,E,Transient,Canceled,2015-06-23,0.0,False,False
27,Resort Hotel,1,60,2015-07-01,2015,July,27,1,2,5,...,BB,PRT,E,E,Transient,Canceled,2015-05-11,0.0,False,False
32,Resort Hotel,1,96,2015-07-01,2015,July,27,1,2,8,...,BB,PRT,E,E,Transient,Canceled,2015-05-29,0.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110280,City Hotel,1,132,2017-04-25,2017,April,17,25,0,0,...,BB,FRA,D,K,Transient,Canceled,2017-04-25,0.0,False,False
111355,City Hotel,1,4,2017-06-05,2017,June,23,5,1,0,...,BB,PRT,A,A,Transient,Canceled,2017-06-05,0.0,False,False
111924,City Hotel,1,7,2017-05-31,2017,May,22,31,0,1,...,BB,PRT,A,A,Transient,Canceled,2017-05-31,0.0,False,False
111925,City Hotel,1,6,2017-07-17,2017,July,29,17,1,0,...,BB,PRT,A,D,Transient,No-Show,2017-07-17,0.0,False,False
117295,City Hotel,1,0,2017-08-02,2017,August,31,2,0,2,...,BB,PRT,A,C,Transient,No-Show,2017-08-02,0.0,False,False

In [ ]:
df.groupby('has_kids1').is_canceled.value_counts()

has_kids1  is_canceled
False      0              69093
           1              40965
True       0               6073
           1               3259
Name: is_canceled, dtype: int64

In [ ]:
df.groupby('has_kids1').is_canceled.value_counts()[1]

40965

In [ ]:
len(df[df['has_kids1']==False])

110058

In [ ]:
Churn_rate = [round(df.groupby('has_kids1').is_canceled.value_counts()[1]/len(df[df['has_kids1']==False]),ndigits=4)*100, \
              round(df.groupby('has_kids1').is_canceled.value_counts()[3]/len(df[df['has_kids1']==True]),ndigits=4)*100\
              ]

In [ ]:
Churn_rate

[37.22, 34.92]